name: Build

on:
  push:
    branches:
    - master
    - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run main script
      shell: bash
      run: |
        python build.py
    - name: Upload Client Pack
      uses: actions/upload-artifact@v4
      with:
          name: client
          path: |
            buildOut/client.zip
    - name: Upload Cleanroom Pack
      uses: actions/upload-artifact@v4
      with:
          name: cleanroom
          path: |
            buildOut/cleanroom.zip
    - name: Upload Server Pack
      uses: actions/upload-artifact@v4
      with:
          name: server
          path: |
            buildOut/server.zip
    - name: Upload ModList
      uses: actions/upload-artifact@v4
      with:
          name: modlist
          path: |
            buildOut/modlist.txt