name: Build

on:
  push:
    branches:
    - master
    - main

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run main script
      shell: bash
      run: |
        python build.py
    - name: Upload Forge Pack
      uses: actions/upload-artifact@v4
      with:
          name: forge
          path: |
            buildOut/forge.zip
    - name: Upload Cleanroom Pack
      uses: actions/upload-artifact@v4
      with:
          name: cleanroom
          path: |
            buildOut/cleanroom.zip