name: Build

on:
  push:
    branches:
    - master
    - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Export Client Pack & ModList
      shell: bash
      run: |
        chmod +x ./packwiz
        ./packwiz curseforge export -o client.zip
        ./packwiz list > modlist.txt
    - name: Download
      shell: bash
      run: |
        serverPack="server.zip"
        cp LICENSE server/
          
        cd server
        java -jar packwiz-installer-bootstrap.jar ../pack.toml
        cd ..

        zip -r $serverPack server
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
          path: |
            client.zip
            server.zip
            modlist.txt